### ISSUE TITLE
Reporting of maximum signal value

### ISSUE THREAD

**Issue by flo-kr** [cremerlab/hplc-py#16]
I noticed that when calling the value for 'Amplitude', the value always seems to be lower than the actual maximal values that can be called through _chrom.unmixed_chromatograms()_ and also lower than the max values recorded in the original chromatogram in the first place. 

To my understanding, 'amplitude' would be the difference between the baseline and the maximal value. Is this the intended idea? 

Best 

Florian

**Comment by gchure** [comment]
Hi Florian,

Thanks for opening an issue. As described [here](https://cremerlab.github.io/hplc-py/methodology/fitting.html), the amplitude is *not* the maximum value--it's a weight applied to a skew normal distribution during the fitting.

For example, these are plots of an amplitude-weighed skew-normal distribution with the same amplitude parameter, but varying skew (alpha):
<img width="576" alt="Screenshot 2024-05-07 at 12 40 21" src="https://github.com/cremerlab/hplc-py/assets/6775595/b69226da-8e41-4e66-a72f-be241edaa2d3">

If you want to know the maximum value of peaks that are not overlapping, you'd be better off either a) using [`scipy.signal.find_peaks`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html) and then use those indices to extract the signal value of those indices, or b) you could get these indices from `hplc-py` by looking at the attribute `Chromatogram._peak_indices`.  

It would be pretty simple to add a `height` or `maximum` value in quantities returned by `fit_peaks`. I will look at that as soon as I have a chance, but you (or anyone else) are welcome to submit a pull request with the change.
